Recup donnees esin
WildCodeSchool/tours-0320-php-rhc-cpias pull request #12
Opened 2020-06-16 13:35 UTC by Frutios

Récupération des fichiers csv et persistance en base de données

2020-06-16 14:12 UTC, Lechars approved these changes
Clean Code Fraicheur

2020-06-16 14:56 UTC, RomainClair requested changes
The public/uploads/xxx.txt files are work files that are not supposed to be in the repository.

The Upload class should not be an entity and it's name property is in fact an UploadedFile, it should have a more relevant name.

SignalementEsin & EsinSuite should probably be linked together.

You should flush only once.

It'll be a good idea to have less code in the controller by deporting it in the entities or in a service.

The best practice is to have form buttons in templates, not in the Type class.

You probably should think about constraints in Entities for validation.

You should use english in your code.

2020-06-17 15:19 UTC, Sarah240 approved these changes
je pense que c'est good

2020-06-18 12:40 UTC, RomainClair approved these changes

2020-06-18 12:40 UTC, merged