Upload csv
WildCodeSchool/tours-0320-php-rhc-cpias pull request #3
Opened 2020-06-04 09:56 UTC by Frutios

2020-06-05 07:24 UTC, Lechars commented on templates/base.html.twig
>          {% endblock %}
peut etre créer une vue qui peut s'inclure dans la vue que je vais push (j'espère ajd) plutot que de mettre tas vu dans le base.twig.html , je pense qu'il vaut mieux pas toucher au twig de base. bisoux <3

2020-06-05 07:26 UTC, Lechars requested changes
#Un petit changement vite fait sur le base.twig.html j'ai mis un comment a ce niveau

2020-06-05 10:11 UTC, Lechars approved these changes

2020-06-09 10:01 UTC, RomainClair requested changes
The view construction sould be simplified : 2 files to add only one usefull line is a lot !
And the view probably should be integrated to the base layout.

2020-06-09 10:01 UTC, RomainClair commented on src/Controller/UploadController.php
> +            $fileName = md5(uniqid()).'.'.$file->guessExtension();
Using md5 on a uniqid is probably not necessary

2020-06-09 10:01 UTC, RomainClair commented on src/Controller/UploadController.php
> +            $upload->setName($fileName);
Changing the upload object's name just before destroying is useless

2020-06-10 07:28 UTC, Sarah240 approved these changes
je pense que c'est ok je ne vois pas de problème

2020-06-10 07:33 UTC, RomainClair approved these changes
Should Upload.php really be an Entity : you'll have to think about it in the future

2020-06-10 07:33 UTC, merged