Zoom
WildCodeSchool/tours-0320-php-rhc-cpias pull request #89
Opened 2020-07-28 18:09 UTC by Lechars

Le Zoom

2020-07-28 18:15 UTC, Frutios approved these changes

2020-07-29 08:53 UTC, RomainClair requested changes

2020-07-29 08:53 UTC, RomainClair commented on README.md
> +
Is it really relevant in the readme ?

2020-07-29 09:00 UTC, RomainClair approved these changes

2020-07-29 09:00 UTC, merged